global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'eureka-server:8761'
          - 'api-gateway:8080'
          - 'product-quote-service:8081'
          - 'order-service:8082'
          - 'docgen-service:8083'
